<?php

namespace AppBundle\Repository;

/**
 * InvoiceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceItemRepository extends \Doctrine\ORM\EntityRepository
{
}
