<?php

namespace AppBundle\Repository;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageRepository extends \Doctrine\ORM\EntityRepository
{
}
