<?php

namespace AppBundle\Repository;

/**
 * ProductAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
