<?php

namespace AppBundle\Repository;

/**
 * ProductDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
