<?php

namespace AppBundle\Repository;

/**
 * SalesOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
