<?php

namespace AppBundle\Repository;

/**
 * ShipmentItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentItemRepository extends \Doctrine\ORM\EntityRepository
{
}
