security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            anonymous: ~
            http_basic: ~
        util:
            pattern: ^/image
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/tasks/, role: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/catalog/, role: ROLE_USER }
        - { path: ^/weborders/, role: [ ROLE_CUSTOMER, ROLE_ADMIN ] }
        - { path: ^/dashboard, role: [ ROLE_CUSTOMER, ROLE_ADMIN ] }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_CUSTOMER:    ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN