# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    erp_one_connector_service:
        class: AppBundle\Service\ErpOneConnectorService
        arguments: [ "%erp_server%", "%erp_username%", "%erp_password%", "%erp_company%", "%erp_appname%" ]
        
    erp_one_product_service:
        class: AppBundle\Service\ErpOneProductService
        arguments: [ "@erp_one_connector_service", "@doctrine.orm.entity_manager" ]
        
    erp_one_order_service:
        class: AppBundle\Service\ErpOneOrderService
        arguments: [ "@erp_one_connector_service", "@doctrine.orm.entity_manager" ]
        
    catalog_import_service:
        class: AppBundle\Service\CatalogImportService
        arguments: [ "@doctrine.orm.entity_manager" ]